- name: Reboot node after NVIDIA driver install
  reboot:
    msg: "Rebooting node to finalize NVIDIA driver installation"
    connect_timeout: 5
    reboot_timeout: 600
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime

- name: Restart containerd
  ansible.builtin.systemd:
    name: containerd
    state: restarted
    enabled: yes
    daemon_reload: yes
