---
- name: Enable CRB repository (AlmaLinux/Rocky 10)
  command: dnf config-manager --set-enabled crb
  changed_when: false
  when: ansible_os_family == "RedHat"

- name: Install EPEL Release for AlmaLinux 10
  dnf:
    name: https://dl.fedoraproject.org/pub/epel/epel-release-latest-10.noarch.rpm
    state: present
    disable_gpg_check: yes
  when: ansible_os_family == "RedHat"

- name: Set SELinux to permissive mode (runtime)
  ansible.builtin.command: setenforce 0
  become: yes
  changed_when: false
  failed_when: false

- name: Persistently set SELinux to permissive mode in config
  ansible.builtin.lineinfile:
    path: /etc/selinux/config
    regexp: '^SELINUX='
    line: 'SELINUX=permissive'
    state: present
  become: yes

- name: Install kernel-modules-extra for the current kernel version
  ansible.builtin.dnf:
    name: "kernel-modules-extra-{{ ansible_kernel }}"
    state: present
  become: yes
  when: ansible_os_family == "RedHat"
  notify: Reboot node if kernel modules changed

- name: Disable swap
  command: swapoff -a
  changed_when: false

- name: Remove swap from /etc/fstab
  replace:
    path: /etc/fstab
    regexp: '^(.*swap.*)$'
    replace: '# \1'

- name: Load kernel modules for Kubernetes networking
  modprobe:
    name: "{{ item }}"
    state: present
  loop:
    - overlay
    - br_netfilter

- name: Ensure net.bridge.bridge-nf-call-iptables is set to 1
  sysctl:
    name: net.bridge.bridge-nf-call-iptables
    value: '1'
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: yes

- name: Ensure net.ipv4.ip_forward is set to 1
  sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_file: /etc/sysctl.d/99-kubernetes-cri.conf
    reload: yes

# Containerd Installation (Example for AlmaLinux/RHEL-based)
- name: Install containerd prerequisites (AlmaLinux/RHEL)
  dnf:
    name:
      - yum-utils
      - device-mapper-persistent-data
      - lvm2
    state: present
  when: ansible_os_family == "RedHat"

- name: Add Docker CE repository (for containerd dependencies often) (AlmaLinux/RHEL)
  command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo
  args:
    creates: /etc/yum.repos.d/docker-ce.repo
  when: ansible_os_family == "RedHat"

- name: Install containerd.io
  dnf:
    name: containerd.io
    state: present

- name: Create containerd config directory
  file:
    path: /etc/containerd
    state: directory

- name: Generate default containerd config
  ansible.builtin.command: containerd config default
  register: containerd_default_config
  changed_when: false

- name: Generate default containerd config to /etc/containerd/config.toml
  ansible.builtin.command: containerd config default
  register: containerd_config_default_output
  changed_when: false

- name: Write the default config to file
  ansible.builtin.copy:
    content: "{{ containerd_config_default_output.stdout }}"
    dest: /etc/containerd/config.toml
    owner: root
    group: root
    mode: '0644'
  notify: Restart containerd

- name: Ensure SystemdCgroup is true in containerd config
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    # This regex finds 'SystemdCgroup = false' possibly with spaces around '='
    regexp: '^(\s*SystemdCgroup\s*=\s*)false'
    replace: '\1true'
  notify: Restart containerd

- name: Ensure CRI plugin is enabled in containerd config
  ansible.builtin.replace:
    path: /etc/containerd/config.toml
    # This regex specifically targets 'disabled_plugins = ["cri"]'
    # and changes it to 'disabled_plugins = []'
    regexp: '^(\s*disabled_plugins\s*=\s*\[")cri("\]\s*)$'
    replace: '\1\2'
  notify: Restart containerd

# Kubernetes components installation (Example for AlmaLinux/RHEL YUM repo)
- name: Add Kubernetes YUM repository (v1.33)
  copy:
    dest: /etc/yum.repos.d/kubernetes.repo
    content: |
      [kubernetes]
      name=Kubernetes
      # Using the CDN baseurl that pkgs.k8s.io redirected to FOR PACKAGES:
      baseurl=https://prod-cdn.packages.k8s.io/repositories/isv:/kubernetes:/core:/stable:/v{{ kubernetes_version_minor }}/rpm/
      enabled=1
      gpgcheck=1
      # GPGKey URL from official RHEL instructions and your historical pattern:
      # This is the key referenced by the repomd.xml metadata.
      gpgkey=https://pkgs.k8s.io/core:/stable:/v{{ kubernetes_version_minor }}/rpm/repodata/repomd.xml.key
      exclude=kubelet kubeadm kubectl cri-tools kubernetes-cni
    mode: '0644'

- name: Install kubelet, kubeadm, kubectl (AlmaLinux/RHEL)
  dnf:
    name:
      - "kubelet-{{ kubernetes_version }}"
      - "kubeadm-{{ kubernetes_version }}"
      - "kubectl-{{ kubernetes_version }}"
    state: present
    disable_excludes: kubernetes
  when: ansible_os_family == "RedHat"
  notify: Enable kubelet

- name: Hold Kubernetes package versions (AlmaLinux/RHEL)
  lineinfile:
    path: /etc/dnf/plugins/versionlock.list # or /etc/yum/pluginconf.d/versionlock.list
    regexp: "^{{ item }}-"
    line: "{{ item }}-{{ kubernetes_version }}.*" # Or more specific lock
    create: yes
  loop:
    - kubelet
    - kubeadm
    - kubectl
  when: ansible_os_family == "RedHat"
