---
- name: Download & install NVIDIA GPG key (Ubuntu 22.04)
  ansible.builtin.apt_key:
    url: https://nvidia.github.io/libnvidia-container/gpgkey
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('22.04', '==')

- name: Create APT sources file for NVIDIA Container Toolkit (Ubuntu 22.04)
  ansible.builtin.shell: |
    distribution=$(. /etc/os-release;echo $ID$VERSION_ID) \
      && curl -fsSL https://nvidia.github.io/libnvidia-container/gpgkey \
           | sudo gpg --dearmor -o /usr/share/keyrings/nvidia-container-toolkit-keyring.gpg \
      && curl -s -L https://nvidia.github.io/libnvidia-container/$distribution/libnvidia-container.list \
           | sed 's#deb https://#deb [signed-by=/usr/share/keyrings/nvidia-container-toolkit-keyring.gpg] https://#g' \
           | sudo tee /etc/apt/sources.list.d/nvidia-container-toolkit.list
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('22.04', '==')

- name: Update apt cache after adding NVIDIA repo (Ubuntu 22.04)
  ansible.builtin.apt:
    update_cache: yes
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('22.04', '==')

- name: Install NVIDIA Container Toolkit (Ubuntu 22.04)
  ansible.builtin.apt:
    name: nvidia-container-toolkit
    state: present
  when:
    - ansible_distribution == "Ubuntu"
    - ansible_distribution_version is version('22.04', '==')
  notify: Restart containerd

- name: Configure Containerd for NVIDIA
  ansible.builtin.command: nvidia-ctk runtime configure --runtime=containerd
  become: true
