---
- name: Prepare all nodes for Kubernetes
  hosts: k8s_cluster
  roles:
  - role: common
  tags:
  - configure_k8s

- name: Initialise Kubernetes Control Plane
  hosts: control_plane
  roles:
  - role: control_plane
  tags:
  - configure_control_plane

- name: Join CPU and GPU Worker Nodes to the Cluster
  hosts: workers
  roles:
  - role: worker_nodes
  tags:
  - configure_workers

- name: Setup GPU Worker Nodes and Join to Cluster
  hosts: gpu_workers
  roles:
  - role: gpu_nodes
  tags:
  - configure_gpu_workers
